version: '3.4'

services:

  bot:
    container_name: bot
    image: bot_image
    build:
      context: ./bot
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env

  db:
    container_name: db
    image: db_image
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}

  db_repl:
    container_name: db_repl
    image: db_repl_image
    build:
      context: ./db_repl
      dockerfile: Dockerfile
      args:
        REPL_USER: ${DB_REPL_USER}
    environment:
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_REPL_PASSWORD}
    ports:
      - ${DB_REPL_PORT}:${DB_PORT}
    depends_on:
      - db
