version: '3.4'

services:
  bot_image:
    image: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    tty: true
    env_file:
      - .env
  db_image:
    image: db
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_host
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
