version: '3.4'

services:
  bot_image:
    image: bot_image
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    tty: true
    env_file:
      - .env
  db:
    image: db_image
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: |
      postgres 
      -c archive_mode=on
      -c archive_command='cp %p /oracle/pg_data/archive/%f'
      -c max_wal_senders=10 
      -c wal_level=replica
      -c wal_log_hints=on 
      -c log_replication_commands=on
      -c logging_collector=on
      -c password_encryption=scram-sha-256
  db_repl:
    image: db_repl_image
    build:
      context: ./db_repl
      dockerfile: Dockerfile
      args:
      - HOST=${DB_HOST}
      - REPL_USER=${DB_REPL_USER}
      - REPL_PASSWORD=${DB_REPL_PASSWORD}
    container_name: db_repl
    environment:
      - POSTGRES_PASSWORD=${DB_REPL_PASSWORD}
      - POSTGRES_USER=${DB_REPL_USER}
    env_file:
      - .env
    ports:
      - ${DB_REPL_PORT}:${DB_PORT}
    command: |
      bash -c "
      apk add expect && \
      ./script.sh
      "
    depends_on:
      - ${DB_HOST}